# Generated by Django 5.0.7 on 2024-08-08 05:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor_app', '0006_remove_processedimage_original_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Image', max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='images',
            name='name',
            field=models.CharField(default='Image', max_length=256),
        ),
        migrations.AddField(
            model_name='images',
            name='album_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album_images', to='processor_app.albums'),
        ),
    ]
