# Generated by Django 5.0.7 on 2024-08-08 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processor_app', '0008_albums_uploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albums',
            name='edited_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
